language: python
python:
    "2.7_with_system_site_packages"

install:
    ./makepackage.sh

script:
    - sudo dpkg -i ./.build/fusepp_0.1-1.deb || true
    - sudo apt-get -f install --yes
    - sudo pip install psutil --upgrade
    - sudo pip install fusepy
    - /usr/local/bin/fusepp.py --test
    - sudo dpkg -r fusepp
    - [ ! -f /usr/local/bin/fusepp.py ]

notifications:
    email:
        - matyas.vegh@gmail.com
    on_success: change
    on_failure: always
