language: python
python:
    - "2.7"

install:
    ./makepackage.sh

script:
    - sudo dpkg -i ./.build/fusepp_0.1-1.deb || true
    - sudo apt-get -f install --yes
    - sudo pip install psutil --upgrade
    - /usr/local/bin/fusepp.py --test

notifications:
    email:
        - matyas.vegh@gmail.com
    on_success: change
    on_failure: always
